// v1.4.7 withdrawal: move generator-produced pages OUT of content/ into _withdrawn/.
// Reversible: manifest-first, fs.renameSync only, never a file delete.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve('.');
const CONTENT = path.join(ROOT, 'content', 'v1.4.7');
const WITHDRAWN = path.join(ROOT, '_withdrawn', 'v1.4.7');
const KEEP_LIST = path.join(ROOT, '_v147_keep_whitelist.txt');
const MANIFEST = path.join(WITHDRAWN, 'MANIFEST-20261002.json');
const MODE = process.argv[2]; // manifest | move | verify

const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

function walkMd(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walkMd(p, out);
    else if (e.name.endsWith('.md')) out.push(p);
  }
  return out;
}

const keep = fs.readFileSync(KEEP_LIST, 'utf8').split(/\r?\n/).map((s) => s.trim()).filter(Boolean);
const keepSet = new Set(keep);

// Evidence read off each page; NOT a classifier — the whitelist decided the move set.
function basis(abs) {
  const t = fs.readFileSync(abs, 'utf8');
  if (t.includes('<!-- v147-skeleton -->')) {
    return 'carries <!-- v147-skeleton --> marker; frontmatter description states auto-generated skeleton (tools/_v147_skeleton.mjs)';
  }
  return 'generator-produced directory index page (machine-built frontmatter + exhaustive sorted leaf listing), no hand-written body; absent from verified keep-list';
}

function buildRecords() {
  const all = walkMd(CONTENT);
  const move = all.filter((p) => !keepSet.has(path.relative(CONTENT, p).split(path.sep).join('/'))).sort();
  if (all.length !== keep.length + move.length) {
    throw new Error(`arithmetic does not close: ${all.length} != ${keep.length} + ${move.length}`);
  }
  const missing = keep.filter((p) => !fs.existsSync(path.join(CONTENT, p)));
  if (missing.length) throw new Error('whitelist paths missing on disk: ' + missing.join(', '));
  return move.map((abs) => {
    const src = rel(abs);                       // content/v1.4.7/<lang>/...
    const sub = src.slice('content/v1.4.7/'.length);
    const lang = sub.split('/')[0];
    return {
      source: src,
      target: `_withdrawn/v1.4.7/${lang}/${sub.slice(lang.length + 1)}`,
      bytes: fs.statSync(abs).size,
      basis: basis(abs),
    };
  });
}

if (MODE === 'manifest') {
  const records = buildRecords();
  fs.mkdirSync(WITHDRAWN, { recursive: true });
  fs.writeFileSync(MANIFEST, JSON.stringify({
    version: 'v1.4.7',
    date: '20261002',
    timestamp: new Date().toISOString(),
    mode: 'move-out (reversible); fs.renameSync only; no rm, no git rm, no file delete',
    generatedBy: '_v147_withdraw.mjs',
    reversible: true,
    undo: 'node -e "const fs=require(\'fs\'),p=require(\'path\'),m=require(\'./_withdrawn/v1.4.7/MANIFEST-20261002.json\');for(const r of m.moved){fs.mkdirSync(p.dirname(r.source),{recursive:true});fs.renameSync(r.target,r.source)}"  // rename every target back to source',
    keepList: '_v147_keep_whitelist.txt',
    keepListPolicy: 'frozen, hand-verified page-by-page by the lead; NOT re-derived here. Known false positive retained on purpose: zh/en architecture/sdk-overview.md document the AutoGenerated/CodeGenerator exclusion rule and are hand-written.',
    keptCount: keep.length,
    kept: keep,
    movedCount: records.length,
    moved: records,
  }, null, 2));
  console.log('manifest_written=' + rel(MANIFEST) + ' records=' + records.length);
}

if (MODE === 'move') {
  const m = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  let moved = 0, failed = [];
  for (const r of m.moved) {
    const src = path.join(ROOT, r.source), dst = path.join(ROOT, r.target);
    if (!fs.existsSync(src)) { failed.push([r.source, 'source missing']); continue; }
    if (fs.existsSync(dst)) { failed.push([r.target, 'target already exists']); continue; }
    fs.mkdirSync(path.dirname(dst), { recursive: true });
    try { fs.renameSync(src, dst); moved++; }
    catch (e) { failed.push([r.source, e.message]); }
  }
  // Prune directories left empty inside content/v1.4.7 (files only, never a file delete).
  const pruned = [], skipped = [];
  for (const lang of ['en', 'zh']) {
    for (const e of fs.readdirSync(path.join(CONTENT, lang), { withFileTypes: true })) {
      if (!e.isDirectory()) continue;
      const d = path.join(CONTENT, lang, e.name);
      const entries = fs.readdirSync(d);
      if (entries.length !== 0) { skipped.push(`${rel(d)} (${entries.length} entries)`); continue; }
      fs.rmdirSync(d); pruned.push(rel(d));
    }
  }
  console.log('moved=' + moved + ' failed=' + failed.length);
  if (failed.length) console.log('FAILURES=' + JSON.stringify(failed, null, 1));
  console.log('pruned_dirs=' + pruned.length + ' ' + JSON.stringify(pruned));
  console.log('skipped_dirs=' + JSON.stringify(skipped));
}