// Rank candidate (non-deep_pass, non-noise) pages in campaign-ext / mission-ext by inbound link count.
import { readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, posix } from 'path';

const CONTENT = 'content';
const cov = JSON.parse(readFileSync('tools/data/handwritten-coverage-v145-zh.json', 'utf8'));
const deep = new Set(cov.deep_pass_paths || []);
const NOISE = /(Platform|Steamworks|Newtonsoft|AutoGenerated|ThirdParty|EOS|Wwise|Steam)/i;

function walk(dir, acc = []) {
  for (const e of readdirSync(dir)) {
    const p = posix.join(dir, e);
    const s = statSync(p);
    if (s.isDirectory()) walk(p, acc);
    else if (e.endsWith('.md')) acc.push(p);
  }
  return acc;
}

function normalize(baseRel, target) {
  if (/^https?:\/\//.test(target)) return null;
  let t = target.split('#')[0].split('?')[0];
  if (t.endsWith('.md')) t = t.slice(0, -3);
  else if (t.endsWith('/')) t = t.slice(0, -1);
  if (t === '' || t === '.') return null;
  if (t.startsWith('/')) return posix.normalize(t.replace(/^\/+/, ''));
  return posix.normalize(posix.join(posix.normalize(baseRel), t));
}

const all = walk(CONTENT);
const inbound = new Map();
const linkRe = /\[[^\]]*\]\(([^)\s]+)\)/g;
for (const f of all) {
  const rel = posix.normalize(f);
  const baseRel = posix.dirname(rel);
  let txt;
  try { txt = readFileSync(f, 'utf8'); } catch { continue; }
  let m;
  while ((m = linkRe.exec(txt))) {
    const abs = normalize(baseRel, m[1]);
    if (!abs) continue;
    if (!inbound.has(abs)) inbound.set(abs, new Set());
    inbound.get(abs).add(rel);
  }
}

const targets = all.filter((f) => {
  const rel = posix.normalize(f);
  if (!rel.includes('v1.4.5/zh/api/campaign-ext/') && !rel.includes('v1.4.5/zh/api/mission-ext/')) return false;
  if (deep.has(rel)) return false;
  if (NOISE.test(rel)) return false;
  if (rel.endsWith('_index.md')) return false;
  return true;
});

const rows = targets.map((p) => {
  const abs = posix.normalize(p.replace(/\.md$/, ''));
  return { p, cnt: inbound.get(abs)?.size || 0 };
});
rows.sort((a, b) => b.cnt - a.cnt);
console.log('candidate (non-deep, non-noise) pages:', targets.length);
console.log('with >=1 inbound:', rows.filter((r) => r.cnt > 0).length);
console.log('TOP 80 by inbound:');
for (const r of rows.slice(0, 80)) console.log(String(r.cnt).padStart(4), r.p);
writeFileSync('tools/_rank_waveb_out.json', JSON.stringify(rows.slice(0, 120), null, 0));
