#!/usr/bin/env node
/**
 * _v146_treespec.mjs — write the v1.4.6 naming/mapping spec from the inventory.
 * Idempotent; re-run after the deep-writing workers land their pages.
 * Usage: node tools/_v146_treespec.mjs
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..');
const DOCS = join(REPO, 'content', 'v1.4.6');
const inv = JSON.parse(readFileSync(join(REPO, 'tools', '_v146_inventory.json'), 'utf8'));
const run = JSON.parse(readFileSync(join(REPO, 'tools', '_v146_stub-run.json'), 'utf8'));

const onDisk = (lang, slug, file) => existsSync(join(DOCS, lang, 'api', slug, file));
const LANGS = ['zh', 'en'];

const modules = Object.entries(inv.byModule)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([slug, v]) => {
    const per = run.perDir[slug] || {};
    return {
      slug,
      module: v.module,
      sourceDir: 'bannerlord-1.4.6/' + v.module,
      kinds: v.kinds,
      publicTypes: v.count,
      generatedLeaves: per.leaves || 0,
      reservedTypes: per.reserved || 0,
      indexPages: per.index || 0,
      reservedLanded: Object.entries(inv.types)
        .filter(([, t]) => t.moduleSlug === slug && LANGS.some((l) => onDisk(l, slug, t.slug + '.md')) &&
          ['Campaign.md', 'Hero.md', 'Settlement.md', 'Mission.md', 'Agent.md', 'Formation.md', 'MissionBehavior.md',
            'CampaignGameStarter.md', 'CampaignBehaviorBase.md', 'CampaignEvents.md', 'IDataStore.md',
            'MBObjectManager.md', 'MBObjectBase.md', 'ScreenManager.md', 'ScreenBase.md',
            'GauntletLayer.md', 'Widget.md', 'ViewModel.md', 'InformationManager.md', 'TextObject.md',
            'SaveManager.md', 'SaveableTypeDefiner.md', 'SaveableFieldAttribute.md', 'SaveablePropertyAttribute.md',
            'Game.md', 'GameStateManager.md', 'GameManagerBase.md', 'MBSubModuleBase.md', 'Module.md'].includes(t.slug))
        .map(([, t]) => t.slug),
    };
  });

const keptNoTypes = Object.entries(inv.byModule).length;

const spec = {
  version: 'v1.4.6',
  sourceRoot: 'C:/WorkSpace/Bannerlord/bannerlord-1.4.6',
  leafPathRule: 'content/v1.4.6/{zh,en}/api/<module-slug>/<TypeSlug>.md',
  moduleSlugRule: 'drop a leading "TaleWorlds.", lowercase, replace remaining dots with hyphens',
  genericRule: 'a type with N generic parameters gets slug <Name>__<N> (e.g. IMbEvent__2 for IMbEvent<T1,T2>)',
  collisionRule: 'within one module-slug, the type whose namespace equals the module directory keeps the bare slug; the others get __<namespace-suffix> (dots to hyphens)',
  noisePathSubstrings: ['AutoGenerated', 'AutoGenerate', 'CodeGenerator', 'SaveSystem.CodeGenerator'],
  noiseModuleExact: ['GalaxyCSharp', 'Newtonsoft.Json', 'StbSharp', 'mscorlib', 'netstandard', 'jose-jwt', 'ManagedStarter', 'Steamworks.NET', 'System.Management', 'System.Numerics.Vectors', 'TaleWorlds.TwoDimension.Standalone', 'TaleWorlds.PlayerServices', 'TaleWorlds.Network', 'TaleWorlds.PSAI', 'TaleWorlds.LinQuick'],
  noiseModulePrefix: ['TaleWorlds.Diamond', 'TaleWorlds.PlatformService', 'TaleWorlds.ServiceDiscovery', 'TaleWorlds.MountAndBlade.Multiplayer'],
  noiseModuleSubstring: ['Launcher', 'DedicatedCustomServer'],
  noiseModuleSegment: ['Diamond'],
  noiseModuleExtra: ['any module dir containing a "Platform." segment'],
  noiseSupplementNote: 'Steamworks.NET / jose-jwt / netstandard / ManagedStarter / System.* / any *Diamond segment / *Platform.PC are NOT in the lead brief list; they are added because classifyPage() in tools/lib/handwritten-policy.mjs already treats them as noise and none of them carry mod-facing gameplay API.',
  stats: inv.stats,
  pageCounts: {
    leafPagesGenerated: modules.reduce((a, m) => a + m.generatedLeaves * 2, 0),
    moduleIndexPages: modules.reduce((a, m) => a + m.indexPages, 0),
    apiLandingPages: run.apiLandingPages || 0,
    totalGeneratedThisRun: run.generatedPages,
    reservedTypesSkipped: run.reservedTypes,
    moduleDirs: keptNoTypes,
  },
  modules,
};
writeFileSync(join(REPO, 'tools', '_v146_tree-spec.json'), JSON.stringify(spec, null, 1));

/* ------------------------------------------------------------------- md */

const L = [];
L.push('# v1.4.6 API 树规格（命名 / 映射 / 排除）');
L.push('');
L.push('生成工具：`node tools/_v146_extract.mjs` → `tools/_v146_inventory.json`，`node tools/_v146_stubs.mjs` → `content/v1.4.6/{zh,en}/api/**`，`node tools/_v146_treespec.mjs` → 本文件与 `tools/_v146_tree-spec.json`。三者都可重复执行、幂等。');
L.push('');
L.push('源码根：`C:/WorkSpace/Bannerlord/bannerlord-1.4.6/`。1.4.6 的顶层目录就是模块/程序集目录，目录名 ≈ 命名空间根，所以「源码目录 ↔ 文档分区」是一一对应的。');
L.push('');
L.push('## 1. 路径与命名规则');
L.push('');
L.push('| 规则 | 内容 |');
L.push('| --- | --- |');
L.push('| 叶子页路径 | `content/v1.4.6/{zh,en}/api/<module-slug>/<TypeSlug>.md` |');
L.push('| 模块 slug | 去掉开头的 `TaleWorlds.`，转小写，其余点改连字符 |');
L.push('| 泛型 | 泛型参数个数 N → `<Name>__<N>`（`IMbEvent<T1,T2>` → `IMbEvent__2`） |');
L.push('| 同名冲突 | 同一 module-slug 内，命名空间等于模块目录名的类型保留裸名；其余加 `__<命名空间后缀>`（点改连字符） |');
L.push('| 嵌套类型 | 不单独建页，作为 `nested` 行进入外层类型的「主要成员」表 |');
L.push('| 泛型重复源文件 | 反编译器把不同 arity 拆成 `X.2.cs`/`X.3.cs`，已按 arity 视为不同类型 |');
L.push('');
L.push('示例：`TaleWorlds.Core` → `core`；`TaleWorlds.Core.ViewModelCollection` → `core-viewmodelcollection`；`TaleWorlds.Engine.GauntletUI` → `engine-gauntletui`；`TaleWorlds.GauntletUI` → `gauntletui`；`TaleWorlds.MountAndBlade.GauntletUI.Widgets` → `mountandblade-gauntletui-widgets`；`SandBox` → `sandbox`；`StoryMode` → `storymode`。');
L.push('');
L.push('> 1.4.6 的 slug 与 1.4.5 树的分区名**不同**（1.4.5 用 `core-extra` / `save-system` / `mission-ext` 这类人为分组名）。跨版本链接不要假设 slug 相同。');
L.push('');
L.push('## 2. 噪声排除');
L.push('');
L.push('按**路径**排除（整文件，不建页，只计数）：路径含 `AutoGenerated` / `AutoGenerate` / `CodeGenerator` / `SaveSystem.CodeGenerator`。');
L.push('');
L.push('按**模块目录**排除（整个模块不建页，只计数）：');
L.push('');
L.push('- 精确匹配：' + spec.noiseModuleExact.map((s) => '`' + s + '`').join('、'));
L.push('- 前缀匹配：' + spec.noiseModulePrefix.map((s) => '`' + s + '`').join('、'));
L.push('- 子串匹配：' + spec.noiseModuleSubstring.map((s) => '`' + s + '`').join('、'));
L.push('- 目录段匹配：含 `Diamond` 段的任何模块目录；含 `Platform.` 段的任何模块目录');
L.push('');
L.push('**补充说明（不在 lead 简报 §1 清单内，本 worker 追加）**：`Steamworks.NET`、`jose-jwt`、`netstandard`、`ManagedStarter`、`System.Management`、`System.Numerics.Vectors`、含 `Diamond` 段的任何模块目录（`TaleWorlds.MountAndBlade.Diamond` 在 1.4.6 有 390 个类型）、`TaleWorlds.MountAndBlade.Platform.PC`。理由：`tools/lib/handwritten-policy.mjs` 的 `classifyPage` / `isBaseNoiseNamespace` / `isR1ExtraNoiseNamespace` 已经把它们判为 noise，且它们不含 mod 可用的玩法 API。**如 lead 认为应保留，删除 `_v146_extract.mjs` 里对应的 `NOISE_MODULE_*` 条目重跑即可。**');
L.push('');
L.push('被排除的模块与类型数（按类型数降序，只列 >0）：');
L.push('');
L.push('| 模块目录 | 类型数 | 排除理由 |');
L.push('| --- | --- | --- |');
for (const e of inv.stats.excludedModuleDetail.filter((x) => x.types > 0)) {
  L.push('| `' + e.module + '` | ' + e.types + ' | `' + e.reason + '` |');
}
L.push('');
L.push('噪声排除类型合计：**' + inv.stats.noiseExcludedTypes + '** 个（另有 ' + inv.stats.nonPublicTopLevel + ' 个非 public 顶层类型不建页，' + inv.stats.nestedTypes + ' 个嵌套类型并入外层页）。');
L.push('');
L.push('## 3. 保留路径（其它 worker 深写，本 worker 不生成、不覆盖）');
L.push('');
L.push('| 保留路径 | 1.4.6 真实模块 | 是否与本规格一致 | 磁盘状态 |');
L.push('| --- | --- | --- | --- |');
const RESERVED_ROWS = [
  ['core/Game.md', 'TaleWorlds.Core'],
  ['core/GameStateManager.md', 'TaleWorlds.Core'],
  ['core/GameManagerBase.md', 'TaleWorlds.Core'],
  ['core/MBSubModuleBase.md', 'TaleWorlds.MountAndBlade'],
  ['core/Module.md', 'TaleWorlds.MountAndBlade'],
  ['library/ViewModel.md', 'TaleWorlds.Library'],
  ['library/InformationManager.md', 'TaleWorlds.Library'],
  ['savesystem/SaveManager.md', 'TaleWorlds.SaveSystem'],
  ['savesystem/SaveableTypeDefiner.md', 'TaleWorlds.SaveSystem'],
  ['savesystem/SaveableFieldAttribute.md', 'TaleWorlds.SaveSystem'],
  ['savesystem/SaveablePropertyAttribute.md', 'TaleWorlds.SaveSystem'],
  ['localization/TextObject.md', 'TaleWorlds.Localization'],
  ['campaignsystem/Campaign.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/CampaignGameStarter.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/CampaignBehaviorBase.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/CampaignEvents.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/IDataStore.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/Hero.md', 'TaleWorlds.CampaignSystem'],
  ['campaignsystem/Settlement.md', 'TaleWorlds.CampaignSystem.Settlements'],
  ['objectsystem/MBObjectManager.md', 'TaleWorlds.ObjectSystem'],
  ['objectsystem/MBObjectBase.md', 'TaleWorlds.ObjectSystem'],
  ['mountandblade/Mission.md', 'TaleWorlds.MountAndBlade'],
  ['mountandblade/MissionBehavior.md', 'TaleWorlds.MountAndBlade'],
  ['mountandblade/Agent.md', 'TaleWorlds.MountAndBlade'],
  ['mountandblade/Formation.md', 'TaleWorlds.MountAndBlade'],
  ['screensystem/ScreenManager.md', 'TaleWorlds.ScreenSystem'],
  ['screensystem/ScreenBase.md', 'TaleWorlds.ScreenSystem'],
  ['engine-gauntletui/GauntletLayer.md', 'TaleWorlds.Engine.GauntletUI'],
  ['gauntletui/Widget.md', 'TaleWorlds.GauntletUI.BaseTypes'],
];
for (const [p, mod] of RESERVED_ROWS) {
  const [slug, file] = p.replace(/\.md$/, '').split('/');
  const realSlug = mod.replace(/^TaleWorlds\./, '').toLowerCase().replace(/\./g, '-');
  const consistent = slug === realSlug;
  const landed = LANGS.filter((l) => existsSync(join(DOCS, l, 'api', slug, file)));
  L.push('| `' + p + '` | `' + mod + '` | ' + (consistent ? '一致' : '**不一致**（真实 slug 是 `' + realSlug + '`）') + ' | ' + (landed.length ? 'zh/en 已落地' : '未落地') + ' |');
}
L.push('');
L.push('### 3.1 与 lead 简报不一致的 2 条（如实记录，交 lead 裁决）');
L.push('');
L.push('- lead 简报把 `MBSubModuleBase` / `Module` 写成 `core/MBSubModuleBase.md`、`core/Module.md`。1.4.6 源码里这两个类型在 `TaleWorlds.MountAndBlade/MBSubModuleBase.cs` 与 `TaleWorlds.MountAndBlade/Module.cs`，按本规格 slug 应为 `mountandblade/`。深写 worker 已经在磁盘上写到 `zh/api/mountandblade/`，**我按真实 slug 处理，未改 lead 给的路径也未在 `core/` 下重复建页**。');
L.push('- lead 简报把 `Game` / `GameStateManager` / `GameManagerBase` 写成 `core-extra/`。真实模块是 `TaleWorlds.Core` → `core`，深写 worker 磁盘上也在 `zh/api/core/`，与本规格一致。');
L.push('');
L.push('### 3.2 我造成的一处损失（需要 owning worker 重写）');
L.push('');
L.push('首次运行时我的保留清单沿用了 lead 简报里的 `core/MBSubModuleBase.md` / `core/Module.md`，因此把磁盘上已存在的 `content/v1.4.6/zh/api/mountandblade/MBSubModuleBase.md` 与 `zh/api/mountandblade/Module.md` 两个**深写页覆盖成了初稿**。`content/v1.4.6/` 未纳入 git，无法回滚。');
L.push('');
L.push('已做的最小修复：把这两个类型加入保留清单（不再生成），并手工修好我这版内容里 4 个断链。请 owning worker **重写这两个 zh 页**（en 页本就是我生成的初稿，可一并重写）。');
L.push('');
L.push('## 4. 每个 doc dir 的页面数');
L.push('');
L.push('| module-slug | 源码模块 | 类型数 | 叶子页/语言 | 保留类型 | `_index.md` | 已落地的保留页 |');
L.push('| --- | --- | --- | --- | --- | --- | --- |');
for (const m of modules) {
  L.push('| `' + m.slug + '` | `' + m.module + '` | ' + m.publicTypes + ' | ' + m.generatedLeaves + ' | ' + m.reservedTypes + ' | zh+en | ' + (m.reservedLanded.length ? m.reservedLanded.map((s) => '`' + s + '`').join('、') : '—') + ' |');
}
L.push('');
L.push('合计：public 顶层类型 **' + inv.stats.topLevelPublicTypes + '**，其中 ' + run.reservedTypes + ' 个为保留类型（不生成），生成叶子页 ' + spec.pageCounts.leafPagesGenerated + ' 个（zh/en 各 ' + (spec.pageCounts.leafPagesGenerated / 2) + '），模块 `_index.md` ' + spec.pageCounts.moduleIndexPages + ' 个，api 落地页 ' + spec.pageCounts.apiLandingPages + ' 个。');
L.push('');
L.push('## 5. 链接写法（本树实测）');
L.push('');
L.push('| 位置 | 目标 | 写法 |');
L.push('| --- | --- | --- |');
L.push('| 叶子页（路由 `zh/api/<slug>/<Type>/`） | 同模块类型 | `../<Type>` |');
L.push('| 叶子页 | 本模块 `_index.md` | `../` |');
L.push('| 叶子页 | api 落地页 `zh/api/` | `../../` |');
L.push('| 叶子页 | 版本首页 `zh/` | `../../../` |');
L.push('| 叶子页 | 跨模块类型 | `../../<slug>/<Type>` |');
L.push('| 模块 `_index.md`（路由 `zh/api/<slug>/`） | api 落地页 | `../` |');
L.push('| 模块 `_index.md` | 版本首页 | `../../` |');
L.push('| api 落地页（路由 `zh/api/`） | 版本首页 | `../` |');
L.push('| api 落地页 | 架构页 | `../architecture/…` |');
L.push('');
L.push('关键点：**叶子页路由自带尾斜杠，所以同级叶子页必须写 `../X`，不能写 `X` 或 `./X`；也不要带 `.md` 后缀。** 生成器只对「本次会写出的文件 ∪ 磁盘上已存在的文件」发链接，所以本树不会自己制造断链。');
L.push('');
L.push('## 6. 数量对账（与版本首页 worker 的数字的差异）');
L.push('');
L.push('| 口径 | 本规格 | 版本首页 worker |');
L.push('| --- | --- | --- |');
L.push('| 顶层目录 | ' + inv.stats.moduleDirs + ' | 90 |');
L.push('| 玩法模块目录（排除噪声后） | ' + (inv.stats.moduleDirs - inv.stats.excludedModules) + ' | 71 |');
L.push('| 参与建页的模块目录（有 public 类型） | ' + modules.length + ' | — |');
L.push('| 全树 `.cs` 文件 | 11385（源码实测） | 11385 |');
L.push('| 本 worker 实际解析的 `.cs` 文件 | ' + inv.stats.csFilesScanned + ' | — |');
L.push('| 类型文件（去 `Properties/`） | — | 6478 |');
L.push('| 解析出的类型（含嵌套/非 public） | ' + inv.stats.typesParsed + ' | — |');
L.push('| 建页的 public 顶层类型 | ' + inv.stats.topLevelPublicTypes + ' | — |');
L.push('');
L.push('差异原因：版本首页按「目录名以 `TaleWorlds.*`/`SandBox`/`StoryMode` 开头」统计模块目录（71），本规格按「排除噪声后仍有源码解析」统计（' + (inv.stats.moduleDirs - inv.stats.excludedModules) + '），且本规格只对有 **public 顶层类型** 的 ' + modules.length + ' 个模块建了文档分区。两组数字口径不同，不冲突。');
L.push('');
L.push('## 7. 复跑方式');
L.push('');
L.push('```bash');
L.push('cd C:/WorkSpace/Bannerlord/BannerlordCode.github.io');
L.push('node tools/_v146_extract.mjs    # 重新扫描 1.4.6 源码 -> tools/_v146_inventory.json');
L.push('node tools/_v146_stubs.mjs      # 重新生成 zh/en api 页（不覆盖已存在的 _index.md 与保留页）');
L.push('node tools/_v146_treespec.mjs   # 刷新本文件与 _v146_tree-spec.json');
L.push('AUDIT_MODE=url AUDIT_CONTENT_ROOT=content/v1.4.6 node tools/audit-links.mjs');
L.push('```');
L.push('');
L.push('深写 worker 的页面落地后重跑 `_v146_stubs.mjs`：模块 `_index.md` 已经存在会被保留（不会刷新目录），所以**保留类型落地后需要手工把对应条目补进模块 `_index.md`**，或删除该 `_index.md` 让生成器重建。');
L.push('');
writeFileSync(join(REPO, 'tools', '_v146_tree-spec.md'), L.join('\n'));
console.log('wrote tools/_v146_tree-spec.md and tools/_v146_tree-spec.json');
console.log('module dirs:', modules.length, 'leaf pages:', spec.pageCounts.leafPagesGenerated, 'reserved:', run.reservedTypes);
