// 逐条人工标注结果：M1 档（加词边界）真实语料的 97 个 unique miss。
// 写死在这里而不是脚本推断 —— 标注是人的判断，脚本只负责核对「一个都没漏标」。
//
// 为什么不用任务书给的 5 类：语料里同时存在「页面明说不是类型的否定句」「文档族名简写
// `GetModified*`」「占位符 `MyBehavior`」「字符串字面值 `Item10`」「反引号里的拼写错误词根
// `Bover`」等，5 类装不下，硬塞会把 80% 的噪声伪装成某一类，反而看不出这把尺的问题。
// 任务书的 5 类里能对上的保留为：REAL_ERROR / FILE_NAME / FIELD_NAME / PROPER_NOUN；
// CAMEL_ARTIFACT 只在 M0 出现（词边界修好后归零）；Suffixes/TypoNamespaces/PointDirs
// 已由别的 worker 从语料里修掉，当前树不再出现（见报告 §3.3）。

export const LABELS = {
  // —— 真缺陷：页面断言了一个源码里根本不存在的类型/成员 ——
  REAL_ERROR: ['HourlyTickHero', 'HourlyTickHeroEvent', 'InventoryOpenedEvent', 'EndCaptivationDetail',
    'PlayerClanChanged', 'MilitiaParty', 'ISaveTypeSerializer', 'Locatable', 'TradeItem',
    'WorkshopWorkshops', 'DynamicHash', 'StaticHash', 'GetMissionCombatDifficulty',
    'OnPostDisplayMissionTick', 'IsMale', 'OnCharacterPortraitPopUpOpenedEvent',
    'OnMissionStateActivatedEvent', 'OnPlayerStartRecruitmentEvent', 'OnPlayerTraitChangedEvent',
    'OnRemoveLayerEvent'],

  // —— .cs 文件名 ——
  FILE_NAME: ['AssemblyInfo'],

  // —— 源码里有更长的真名，页面/提取只取了片段（与 CAMEL_ARTIFACT 不同源：这里是名字被截断，
  //    那边是 lowerCamel 内部大写段被切开）——
  SUFFIX_TRUNC: ['FindObject', 'PlayerUpgradedTroops', 'BallistaBolt', 'NetworkHelper'],

  // —— 检查器的证据域缺口：目录/工程文件里存在，但没有任何 .cs 文本声明过它 ——
  SCOPE_GAP: ['AutoGenerate'],

  // —— 文档族名简写：页面写 `GetModified*` / `KeyPartN` / `Scaled*` ——
  FAMILY_WILDCARD: ['GetModified', 'GetModifiedMount', 'KeyPartN', 'AirFriction', 'ModifyMount',
    'GetRandom', 'ConstructGeneric', 'MonsterSuffix', 'EstimatedAverage', 'Scaled', 'WeightOf',
    'CoverType', 'Define', 'XxxBonus', 'AutoGeneratedGetMemberValueKeyPartN', 'ForUsage'],

  // —— 占位符/示例名（MyBehavior / OnXxx / YourType…）——
  PLACEHOLDER: ['OnXxx', 'HasXxxComponent', 'MyBehavior', 'MyEvent', 'MyKey', 'MyScreen', 'XxxComponent',
    'YourType', 'CanXxx', 'CanXxxObject', 'GetXxx', 'HandleXxx', 'IsXxx', 'ModifyXxx', 'OnFoo',
    'OnMyEvent', 'ScaledXxx', 'SetCustomCameraXxx', 'SetXxxModifier', 'SomeKey',
    'TryGetParameterAsXxx', 'Xxx', 'XxxEvent', 'XxxModel', 'XxxVisible', 'ICustomManager', 'MyLayer',
    'MySaddleComponent', 'MyViewModel'],

  // —— 缩写/专有名词/链接标签 ——
  PROPER_NOUN: ['NRE', 'ABI', 'LINQ', 'LOD', 'NPE', 'Sibling', 'CAS', 'DOM', 'ECS', 'FNV', 'ImGui',
    'POCO', 'XSD', 'XSLT', 'Rebellios', 'Bover', 'SerializeNulls'],

  // —— 页面明说「它不是类型」（否定句），检查器照样报 ——
  NEGATED: ['EncyclopediaVM', 'BaseVM', 'InvalidId', 'Combined'],

  // —— 字符串/绑定路径字面值，不是标识符 ——
  LITERAL_VALUE: ['Item10', 'SubPanel', 'UpperBody', 'FormationGroup'],

  // —— 反引号里引用的真名词根 ——
  WORD_FRAGMENT: ['WithoutAgent'],
};
