import { readFileSync } from 'node:fs';
const files = process.argv.slice(2);
for (const f of files) {
  const src = readFileSync(f, 'utf8');
  const lines = src.split(/\r?\n/);
  const out = [];
  // top-level type declaration
  for (let i = 0; i < lines.length; i++) {
    const L = lines[i];
    if (/^\s*(public|internal|protected)\s+(?:sealed\s+|abstract\s+|static\s+|partial\s+)*(class|interface|struct|enum)\s/.test(L)) {
      out.push(`DECL L${i+1}: ${L.trim()}`);
    }
  }
  let depth = 0, inBlock = false, buf = [];
  for (let i = 0; i < lines.length; i++) {
    let L = lines[i].replace(/\/\/.*$/, '').replace(/\/\*.*?\*\//g, '');
    if (inBlock) { if (L.includes('*/')) inBlock = false; continue; }
    if (L.includes('/*') && !L.includes('*/')) { inBlock = true; continue; }
    const t = L.trim();
    if (!t) continue;
    const isDecl = /^(public|protected|internal|private)\s/.test(t) || /^(public|protected)\s/.test(t);
    if (isDecl && !/^(public|protected|internal|private)\s+(?:readonly\s+)?(?:const\s+)?[A-Za-z_][\w<>\[\],. ]*$/.test(t)) {
      buf.push(t);
      // accumulate until balanced
      let bal = (t.match(/[({<]/g)||[]).length - (t.match(/[)}>]/g)||[]).length;
      let j = i;
      while (bal > 0 && j + 1 < lines.length && buf.length < 12) {
        j++;
        let nx = lines[j].replace(/\/\/.*$/, '');
        if (nx.includes('/*')) { nx = nx.split('/*')[0]; }
        buf.push(nx.trim());
        bal += (nx.match(/[({<]/g)||[]).length - (nx.match(/[)}>]/g)||[]).length;
      }
      const merged = buf.join(' ').replace(/\s+/g,' ').replace(/\s*([({<])/g,'$1').replace(/([)}>])\s*/g,'$1').replace(/\s*;\s*$/,'');
      if (/^(public|protected)\b/.test(merged) && !/AutoGenerated/i.test(merged)) {
        out.push(`L${i+1}: ${merged}`);
      }
      buf = [];
      i = j;
    }
  }
  console.log(`\n===== ${f} (${lines.length} lines) =====`);
  console.log(out.join('\n'));
}
